type StaticAnswer = {
  text: string;
  source: "fallback";
  relatedSection?: string;
  relatedCapability?: string;
};

const unsafe = /(ignore (all |the )?(previous|prior) instructions|system prompt|developer message|read (a |the )?(file|filesystem)|run (a )?(command|shell)|show (the )?(env|environment|secret|token|credential))/i;

export function staticAssistantAnswer(question: string): StaticAnswer {
  const q = question.toLowerCase();
  const id = /\b(apa|siapa|kemampuan|bisa|pengalaman|belajar|tersedia|magang|teknologi|jelaskan)\b/.test(q);
  if (unsafe.test(question)) return { text: id ? "Saya hanya dapat membantu dengan informasi profesional publik dalam portfolio Dikriana. Saya tidak dapat membuka prompt, file, environment, atau menjalankan perintah." : "I can only help with public professional information in Dikriana’s portfolio. I cannot reveal prompts, read files or environment data, or run commands.", source: "fallback" };
  if (/it support|diskominfo|magang|experience|pengalaman/.test(q)) return { text: id ? "Dikriana menjalani magang IT Support di Diskominfo Kota Sukabumi pada Maret–Mei 2022. Aktivitasnya mencakup troubleshooting komputer dan jaringan, instalasi serta konfigurasi software, pengecekan perangkat, dan membantu kebutuhan teknis pengguna." : "Dikriana completed an IT Support internship at Diskominfo Kota Sukabumi from March–May 2022, covering computer and network troubleshooting, software installation and configuration, device checks, and user assistance.", source: "fallback", relatedSection: "experience", relatedCapability: "computer-troubleshooting" };
  if (/backend|express|sqlite|zod|node/.test(q)) return { text: id ? "Capability backend yang terverifikasi dari portfolio ini adalah Node.js, Express, SQLite, dan Zod, dengan evidence pada API, validasi, keamanan, dan penyimpanan contact." : "Verified backend capabilities include Node.js, Express, SQLite, and Zod, evidenced by this portfolio's APIs, validation, security, and contact storage.", source: "fallback", relatedSection: "capabilities", relatedCapability: "express" };
  if (/learn|belajar/.test(q)) return { text: id ? "Dikriana sedang mempelajari pola React dan TypeScript, dasar backend API, automated testing, serta dasar infrastructure dan deployment." : "Dikriana is currently learning React and TypeScript patterns, backend API fundamentals, automated testing, and infrastructure and deployment basics.", source: "fallback", relatedSection: "capabilities" };
  if (/available|availability|tersedia|internship/.test(q)) return { text: id ? "Ya. Dikriana terbuka untuk kesempatan internship." : "Yes. Dikriana is available for internship opportunities.", source: "fallback", relatedSection: "contact" };
  if (/technolog|stack|react|typescript|vite/.test(q)) return { text: id ? "Portfolio ini menggunakan React, TypeScript, Vite, Node.js, Express, SQLite, dan Zod. Ini merupakan project evidence, bukan klaim pengalaman production eksternal." : "This portfolio uses React, TypeScript, Vite, Node.js, Express, SQLite, and Zod as project evidence, not as a claim of external production experience.", source: "fallback", relatedSection: "capabilities" };
  if (/education|pendidikan|campus|kampus/.test(q)) return { text: id ? "Dikriana adalah mahasiswa Teknik Informatika di Muhammadiyah Kota Sukabumi, dengan latar belakang SMK Teknik Komputer dan Jaringan." : "Dikriana is an Informatics Engineering student at Muhammadiyah Kota Sukabumi, with a vocational background in Computer and Network Engineering.", source: "fallback", relatedSection: "education" };
  if (/certif|sertif|bnsp|kkni/.test(q)) return { text: id ? "Dikriana memiliki KKNI Level II Teknik Komputer dan Jaringan dari BNSP, terbit 2023 dan berlaku sampai 2026. Statusnya adalah Previously certified." : "Dikriana earned the BNSP KKNI Level II Computer and Network Engineering certification in 2023. It was valid through 2026 and is listed as Previously certified.", source: "fallback", relatedSection: "education" };
  if (/skill|capabilit|kemampuan|strongest|bisa|what can/.test(q)) return { text: id ? "Evidence terkuat Dikriana adalah pengalaman praktis IT Support dan pembangunan portfolio full-stack ini dengan React, TypeScript, Node.js, Express, SQLite, dan Zod." : "Dikriana’s strongest evidence is practical IT Support experience and building this full-stack portfolio with React, TypeScript, Node.js, Express, SQLite, and Zod.", source: "fallback", relatedSection: "capabilities" };
  return { text: id ? "Informasi tersebut belum tersedia. Anda dapat bertanya tentang experience, capabilities, education, teknologi portfolio, atau availability internship." : "That information is not currently available. You can ask about experience, capabilities, education, portfolio technologies, or internship availability.", source: "fallback" };
}
